
version: '3'

services:

  flask:
    restart: always
    env_file: .env
    build: .
#    ports:
#      - "5005:5005"
    networks:
      - db_network
      - web_network
    volumes:
      - ./docker_data/app-data:/var/www/logs
      - ./docker_data/db-data:/db-data

  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./docker_data/nginx-data:/var/log/nginx
    networks:
      - web_network
    depends_on:
      - flask

networks:
  db_network:
    driver: bridge
  web_network: